name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use Node 16+
      
    - name: Update README with latest blog posts
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        feed_list: 'https://dev.to/feed/rahuldkjain, https://medium.com/feed/@abhishek.04619011622'


